In [5]:
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [31]:
raw_data = pd.read_csv("CAE_dataset.csv")
raw_data.describe()

,Unnamed: 0,0,1,2,3,4,5,6,7,8,9,label,Id
count,385768.000000,383289.000000,383289.000000,383289.000000,383289.000000,383245.000000,383289.000000,383289.000000,383289.000000,383289.000000,383287.000000,385768.000000,385768.000000
mean,192883.500000,107.382212,-256.001944,-0.206103,6.020567,49.830667,47.046577,62.263751,-1.732243,-1.301005,130.782761,0.382059,219.508969
std,111361.773659,354.660944,201.461946,1.877303,5.263088,6.046602,13.363281,36.464088,11.402677,3.371628,16.066772,0.485891,128.401814
min,0.000000,-1510.880073,-1077.847000,-15.624560,-0.731537,0.000000,0.000000,0.000000,-359.308839,-27.481137,-15.000000,0.000000,0.000000
25%,96441.750000,0.221964,-363.713000,-0.521088,-0.133167,50.000000,43.164062,13.451710,-3.511680,-2.561242,132.313600,0.000000,108.000000
50%,192883.500000,8.443681,-225.006900,-0.175699,8.576858,50.000000,50.000000,82.186990,-0.796670,-0.717236,132.445100,0.000000,219.000000
75%,289325.250000,110.097959,-85.935050,0.177281,10.388649,50.000000,50.000000,82.815810,-0.166258,0.109655,132.578700,1.000000,330.000000
max,385767.000000,5624.443885,108.083800,22.013577,22.346231,99.726562,99.755859,95.334230,359.568333,31.297580,144.338000,1.000000,443.000000

In [23]:
y = raw_data['label']
print(y.describe())
y = y.values

count    385768.000000
mean          0.382059
std           0.485891
min           0.000000
25%           0.000000
50%           0.000000
75%           1.000000
max           1.000000
Name: label, dtype: float64

In [32]:
X = raw_data.drop(columns = 'label')

In [37]:
# partition pilot stuff
pilots = raw_data['Id'].values
start = pilots[0]
sep = list() #list of separations
for i in range(len(pilots)):
    if pilots[i] != start:
        sep.append(i)
        start = pilots[i]

[647,
 1306,
 2170,
 2843,
 3438,
 4056,
 4722,
 5432,
 6162,
 6710,
 7236,
 8332,
 9388,
 10347,
 10415,
 11624,
 12497,
 13176,
 13967,
 14655,
 15409,
 15450,
 15985,
 16845,
 17592,
 18367,
 19151,
 19771,
 20625,
 21274,
 21962,
 22716,
 23537,
 24373,
 25003,
 25372,
 26061,
 26760,
 27882,
 29068,
 30262,
 30940,
 31657,
 32363,
 33314,
 34197,
 34463,
 35118,
 35853,
 36558,
 37306,
 38457,
 39424,
 40137,
 41258,
 42431,
 43254,
 43892,
 44848,
 45731,
 46590,
 47252,
 47918,
 48659,
 49234,
 50327,
 51197,
 51873,
 52052,
 53089,
 53789,
 54475,
 55119,
 55809,
 56778,
 57463,
 58743,
 59428,
 59872,
 61009,
 61460,
 61886,
 63068,
 64239,
 65426,
 66206,
 66958,
 67535,
 68269,
 69015,
 70106,
 70858,
 71990,
 72659,
 73361,
 74530,
 75484,
 76457,
 77102,
 77956,
 78696,
 79375,
 80309,
 81196,
 81723,
 82409,
 83594,
 83681,
 84708,
 85399,
 86334,
 86983,
 88173,
 88787,
 89521,
 90260,
 90783,
 91304,
 92011,
 93021,
 93498,
 94155,
 95095,
 96073,
 97266,
 98360,
 99389,
 100094,
 101119,
 101950,
 102656,
 103368,
 104675,
 105421,
 106269,
 107257,
 108020,
 108702,
 109354,
 110309,
 110465,
 111158,
 111832,
 112488,
 113057,
 113670,
 114286,
 115453,
 115624,
 116214,
 116897,
 117599,
 118449,
 119152,
 119839,
 120516,
 121051,
 121770,
 122405,
 123679,
 124920,
 125613,
 126459,
 127141,
 128065,
 128846,
 129540,
 130185,
 131092,
 131727,
 132363,
 133412,
 134262,
 134965,
 135713,
 136435,
 137169,
 137881,
 138604,
 139296,
 139997,
 140704,
 141766,
 142873,
 143842,
 144900,
 145943,
 147185,
 147844,
 148486,
 148720,
 149364,
 150230,
 150894,
 151533,
 152306,
 152976,
 153662,
 154333,
 155585,
 156320,
 157251,
 157981,
 158618,
 159219,
 160409,
 161344,
 162013,
 162673,
 163377,
 164503,
 165231,
 165930,
 166630,
 167635,
 168320,
 169494,
 170231,
 171009,
 171796,
 172883,
 174044,
 174443,
 174852,
 175387,
 176549,
 177225,
 177944,
 178319,
 179345,
 180502,
 181127,
 181885,
 182631,
 182643,
 183755,
 184459,
 185194,
 185910,
 186502,
 187392,
 188474,
 189206,
 189639,
 190198,
 191308,
 191972,
 192803,
 193336,
 194169,
 195522,
 196475,
 197383,
 198245,
 199487,
 200611,
 201365,
 202526,
 203179,
 203467,
 204179,
 205020,
 205957,
 206998,
 207731,
 208371,
 209183,
 210074,
 210792,
 211569,
 212406,
 213150,
 214122,
 215234,
 216124,
 216887,
 217572,
 218203,
 218848,
 219475,
 220466,
 221508,
 222234,
 223061,
 223643,
 224320,
 224929,
 224930,
 225713,
 226396,
 227512,
 228564,
 228717,
 229398,
 230593,
 231280,
 232485,
 233179,
 233566,
 234368,
 235487,
 236608,
 237273,
 238382,
 239055,
 239700,
 240824,
 241785,
 242430,
 243619,
 244638,
 245764,
 246534,
 247349,
 248047,
 248536,
 249603,
 250390,
 251467,
 252523,
 253664,
 254903,
 255817,
 256703,
 258118,
 259355,
 260439,
 261552,
 262685,
 263878,
 264365,
 265131,
 266124,
 266811,
 267842,
 267994,
 268081,
 268981,
 270342,
 271498,
 272361,
 272437,
 273441,
 274584,
 275373,
 275655,
 276348,
 277063,
 277762,
 278652,
 279642,
 280298,
 281538,
 282398,
 283428,
 283779,
 284554,
 285439,
 286739,
 287345,
 287822,
 288585,
 289677,
 290771,
 291865,
 293014,
 293743,
 294471,
 295621,
 296765,
 297807,
 298893,
 299936,
 299945,
 300709,
 301802,
 302788,
 303574,
 304241,
 305515,
 306569,
 307623,
 308368,
 309102,
 309891,
 310015,
 310985,
 311932,
 312840,
 314005,
 314940,
 315667,
 316541,
 317269,
 318165,
 319268,
 320422,
 321547,
 322531,
 323206,
 324439,
 325370,
 326639,
 327411,
 328095,
 328740,
 329576,
 330726,
 331536,
 332766,
 333679,
 334399,
 335590,
 336075,
 336855,
 337775,
 338776,
 338917,
 339952,
 340967,
 342018,
 342899,
 343626,
 345090,
 346464,
 346496,
 347668,
 348678,
 349667,
 350629,
 351911,
 352755,
 353415,
 354509,
 355257,
 356075,
 356321,
 357335,
 358440,
 358988,
 359666,
 360705,
 361621,
 362723,
 363909,
 364613,
 365330,
 366158,
 366880,
 367025,
 367811,
 368704,
 369899,
 370577,
 371257,
 372183,
 373337,
 374418,
 374960,
 375558,
 376218,
 377126,
 378281,
 379049,
 380184,
 381225,
 382433,
 383173,
 384525]

In [38]:
len(sep)

469